import { Component } from '@angular/core';

@Component({
  selector: 'app-product-list',
  templateUrl: './product-list.component.html',
  styleUrl: './product-list.component.css'
})
export class ProductListComponent {
// Dummy products array
  Product = [
  {
    id: 1,
    name: 'Product 1',
    description: 'Description for Product 1',
    brand: 'Brand A',
    gender: 'Male',
    category: 'Clothing',
    size: 'Medium',
    color: 'Blue',
    price: 29.99,
    is_in_inventory: true,
    items_left: 10,
    imageURL: 'https://example.com/product2.jpg',
    slug: 'product-1',
  },
  {
    id: 2,
    name: 'Product 2',
    description: 'Description for Product 2',
    brand: 'Brand B',
    gender: 'Female',
    category: 'Shoes',
    size: '7',
    color: 'Red',
    price: 49.99,
    is_in_inventory: true,
    items_left: 5,
    imageURL: 'https://example.com/product2.jpg',
    slug: 'product-2',
  },
  {
    id: 3,
    name: 'Product 3',
    description: 'Description for Product 3',
    brand: 'Brand C',
    gender: 'Unisex',
    category: 'Accessories',
    size: 'One Size',
    color: 'Black',
    price: 19.99,
    is_in_inventory: false,
    items_left: 0,
    imageURL: 'https://example.com/product3.jpg',
    slug: 'product-3',
  },
  {
    id: 4,
    name: 'Product 4',
    description: 'Description for Product 4',
    brand: 'Brand AB',
    gender: 'Male',
    category: 'Clothing',
    size: 'Medium',
    color: 'Blue',
    price: 29.99,
    is_in_inventory: true,
    items_left: 10,
    imageURL: 'https://example.com/product1.jpg',
    slug: 'product-1',
  },
  {
    id: 5,
    name: 'Product 5',
    description: 'Description for Product 5',
    brand: 'Brand ABC',
    gender: 'Male',
    category: 'Clothing',
    size: 'Medium',
    color: 'Blue',
    price: 29.99,
    is_in_inventory: true,
    items_left: 10,
    imageURL: 'https://example.com/product1.jpg',
    slug: 'product-1',
  },
  {
    id: 6,
    name: 'Product 6',
    description: 'Description for Product 6',
    brand: 'Brand ABCD',
    gender: 'Male',
    category: 'Clothing',
    size: 'Medium',
    color: 'Blue',
    price: 29.99,
    is_in_inventory: true,
    items_left: 10,
    imageURL: 'https://example.com/product1.jpg',
    slug: 'product-1',
  },
  {
    id: 7,
    name: 'Product 7',
    description: 'Description for Product 7',
    brand: 'Brand ABCDE',
    gender: 'Male',
    category: 'Clothing',
    size: 'Medium',
    color: 'Blue',
    price: 29.99,
    is_in_inventory: true,
    items_left: 10,
    imageURL: 'https://example.com/product1.jpg',
    slug: 'product-1',
  },
  {
    id: 8,
    name: 'Product 8',
    description: 'Description for Product 8',
    brand: 'Brand A',
    gender: 'Male',
    category: 'Clothing',
    size: 'Medium',
    color: 'Blue',
    price: 29.99,
    is_in_inventory: true,
    items_left: 10,
    imageURL: 'https://example.com/product1.jpg',
    slug: 'product-1',
  },
  {
    id: 9,
    name: 'Product 9',
    description: 'Description for Product 9',
    brand: 'Brand ABCDEF',
    gender: 'Male',
    category: 'Clothing',
    size: 'Medium',
    color: 'Blue',
    price: 29.99,
    is_in_inventory: true,
    items_left: 10,
    imageURL: 'https://example.com/product1.jpg',
    slug: 'product-1',
  },
  {
    id: 10,
    name: 'Product 10',
    description: 'Description for Product 10',
    brand: 'Brand AD',
    gender: 'Male',
    category: 'Clothing',
    size: 'Medium',
    color: 'Blue',
    price: 29.99,
    is_in_inventory: true,
    items_left: 10,
    imageURL: 'https://example.com/product1.jpg',
    slug: 'product-1',
  }
];
}
