import { Component, Input } from '@angular/core';
import { __values } from 'tslib';

@Component({
  selector: 'app-product-list',
  templateUrl: './product-list.component.html',
  styleUrl: './product-list.component.css'
})
export class ProductListComponent {
// Dummy products array

  Product = [
  {
    id: 1,
    name: 'ITEL',
    description: 'Description for Product 1',
    brand: 'Brand A',
    gender: 'Male',
    category: 'Clothing',
    size: 'Medium',
    color: ['blue', 'orange', 'black', 'red'],
    price: 89.99,
    discountPrice: 3,
    is_in_inventory: true,
    items_left: 10,
    imageURL: '../../assets/images/iphone.webp',
    slug: 'product-1',
  },
  {
    id: 2,
    name: 'Iphone',
    description: 'Description for Product 2',
    brand: 'Brand B',
    gender: 'Female',
    category: 'Shoes',
    size: '7',
    color: ['blue', 'orange', 'black', 'red'],
    price: 49.99,
    is_in_inventory: true,
    items_left: 5,
    imageURL: '../../assets/images/iphone.webp',
    slug: 'product-2',
  },
  {
    id: 3,
    name: 'Samsung',
    description: 'Description for Product 3',
    brand: 'Brand C',
    gender: 'Unisex',
    category: 'Accessories',
    size: 'One Size',
    color: ['blue', 'orange', 'black', 'red'],
    price: 49.99,
    discountPrice: 3,
    is_in_inventory: false,
    items_left: 0,
    imageURL: '../../assets/images/iphone.webp',
    slug: 'product-3',
  },
  {
    id: 4,
    name: 'Infinix',
    description: 'Description for Product 4',
    brand: 'Brand AB',
    gender: 'Male',
    category: 'Clothing',
    size: 'Medium',
    color: ['blue', 'orange', 'black', 'red'],
    price: 29.99,
    is_in_inventory: true,
    items_left: 10,
    imageURL: '../../assets/images/iphone.webp',
    slug: 'product-1',
  },
  {
    id: 5,
    name: 'OnePlus',
    description: 'Description for Product 5',
    brand: 'Brand ABC',
    gender: 'Male',
    category: 'Clothing',
    size: 'Medium',
    color: ['blue', 'orange', 'black', 'red'],
    price: 119.99,
    discountPrice: 3,
    is_in_inventory: true,
    items_left: 10,
    imageURL: '../../assets/images/iphone.webp',
    slug: 'product-1',
  },
  {
    id: 6,
    name: 'Iphone',
    description: 'Description for Product 6',
    brand: 'Brand A',
    gender: 'Male',
    category: 'Clothing',
    size: 'Medium',
    color: ['blue', 'orange', 'black', 'red'],
    price: 59.99,
    is_in_inventory: false,
    items_left: 10,
    imageURL: '../../assets/images/iphone.webp',
    slug: 'product-1',
  },
  {
    id: 7,
    name: 'Samsung',
    description: 'Description for Product 7',
    brand: 'Brand ABCDE',
    gender: 'Male',
    category: 'Clothing',
    size: 'Medium',
    color: ['blue', 'orange', 'black', 'red'],
    price: 29.99,
    is_in_inventory: true,
    items_left: 10,
    imageURL: '../../assets/images/iphone.webp',
    slug: 'product-1',
  },
  {
    id: 8,
    name: 'Iphone',
    description: 'Description for Product 8',
    brand: 'Brand A',
    gender: 'Male',
    category: 'Clothing',
    size: 'Medium',
    color: ['blue', 'orange', 'black', 'red'],
    price: 29.99,
    discountPrice: 3,
    is_in_inventory: true,
    items_left: 10,
    imageURL: '../../assets/images/iphone.webp',
    slug: 'product-1',
  },
  {
    id: 9,
    name: 'Samsung',
    description: 'Description for Product 9',
    brand: 'Brand ABCDEF',
    gender: 'Male',
    category: 'Clothing',
    size: 'Medium',
    color: ['blue', 'orange', 'black', 'red'],
    price: 29.99,
    is_in_inventory: true,
    items_left: 10,
    imageURL: '../../assets/images/iphone.webp',
    slug: 'product-1',
  },
  {
    id: 10,
    name: 'Itel',
    description: 'Description for Product 10',
    brand: 'Brand AD',
    gender: 'Male',
    category: 'Clothing',
    size: 'Medium',
    color: ['blue', 'orange', 'black', 'red'],
    price: 209.99,
    discountPrice: 3,
    is_in_inventory: false,
    items_left: 10,
    imageURL: '../../assets/images/iphone.webp',
    slug: 'product-1',
  },
  {
    id: 10,
    name: 'OnePlus',
    description: 'Description for Product 10',
    brand: 'Brand AD',
    gender: 'Male',
    category: 'Clothing',
    size: 'Medium',
    color: ['blue', 'orange', 'black', 'red'],
    price: 209.99,
    discountPrice: 3,
    is_in_inventory: false,
    items_left: 10,
    imageURL: '../../assets/images/iphone.webp',
    slug: 'product-1',
  },
  {
    id: 10,
    name: 'Itel',
    description: 'Description for Product 10',
    brand: 'Brand AD',
    gender: 'Male',
    category: 'Clothing',
    size: 'Medium',
    color: ['blue', 'orange', 'black', 'red'],
    price: 209.99,
    discountPrice: 3,
    is_in_inventory: false,
    items_left: 10,
    imageURL: '../../assets/images/iphone.webp',
    slug: 'product-1',
  }
];

@Input()
searchText: string = '';

  totalProductCount = this.Product.length;
  totalInStock = this.Product.filter(p => p.is_in_inventory === true).length;
  totalOutOfStock = this.Product.filter(p => p.is_in_inventory === false).length;

  selectedFilterRadioButton: string = 'all';
  onFilterChange(value: string){
    console.log(value);
    this.selectedFilterRadioButton = value;
  }
}
